title: Xavier P. Morelle, PhD
logo: /pictures/PNG2018_presentationXPM_cropped.jpeg
description: CNRS Associate Researcher in Physico-Chemistry of solid polymers
show_downloads: false
google_analytics:

theme: jekyll-theme-minimal
